### ISSUE TITLE
Game Stuck / Tree Rotation

### ISSUE THREAD

**Issue by chameleon-tbn** [Quistar-LAB/TreeAnarchy#11]
After a while - and i can't say if there is any specific action causing it - the game stucks... to explain:

The UI can be clicked but nothing can be selected on the map nor can i unpause the game. I can open any kind of menu and activate any tool... but they are not working... Every time i had this (third time now) i was using Forest Brush and the only tree relevant mod i've changed is yours.

Only option i have after such a stuck is to close the game to desktop using the menu

Please find attached my logs
[output_log.txt](https://github.com/Quistar-LAB/TreeAnarchy/files/6616459/output_log.txt)
[TMPE.log](https://github.com/Quistar-LAB/TreeAnarchy/files/6616461/TMPE.log)

Second Point i had: I excluded Tree Movement Control, as it's functions seems to be included in Tree Anarchy... but for me the Trees do not rotate then...

**Comment by chameleon-tbn** [comment]
After restart for the moment Tree rotation works...

**Comment by Quistar-LAB** [comment]
now... that's a HUGE log file......

'Rennmont' failed to load.
System.NullReferenceException: Object reference not set to an instance of an object
  at LoadPanel.Refresh () [0x00000] in <filename unknown>:0   [Serialization]
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

2,938,819ms | Refreshing package 'Rennmont' [C:\Users\jaeln\AppData\Local\Colossal Order\Cities_Skylines\Saves\Rennmont.crp]  [Packer - Internal]
2,949,573ms | UnifiedUIMod | [Debug]  2,925,725ms | RoundaboutBuilderButton.OnToolChanged(): newTool.namespace = 
Trying to copy properties from null material.

Your city was auto-saving, and this null reference exception occured at LoadPanel.Refresh. I'm not familiar with this invoked method, but it sure does look like unifiedUIMod to me.

There are some other areas that can be considered major issue, but you can start from here

**Comment by Quistar-LAB** [comment]
Another possibility is Prop Painter mod, I always felt this mod was buggy. You can remove it and test.
The reason why I say this is because I had a thorough look through the codes in Prop Painter. My Propitize mod was architecturally copied over from Prop Painter, and I have to say.... its not that good in design.
Anyways, this is another place to look for your problem, based on the output.txt

**Comment by chameleon-tbn** [comment]
Thanks. yes Prop Painter i was on to remove... but forgot :D

**Comment by Quistar-LAB** [comment]
Is the tree rotation working?

**Comment by chameleon-tbn** [comment]
Yes, all seems to be good regarding to your Mod. But i'll do some Stress Test with 150 mods :)

**Comment by chameleon-tbn** [comment]
Tree rotation works using Find It mod but do not work using [Forest Brush](https://steamcommunity.com/sharedfiles/filedetails/?id=1658679290) mod

**Comment by Quistar-LAB** [comment]
Yes you are correct. The original way of random tree rotation was to use Eular math within the global Render of each tree. This added an approximately 15ms drawing each tree, since .Net3.5 does not provide the SIMD vector math instructions. So in order to maintain performance, I had to remove it and do the math individually for each case, whether using tree tool or moveit. I didn't do it for forest brush though

**Comment by chameleon-tbn** [comment]
Will you add that?

**Comment by Quistar-LAB** [comment]
Yes I can, but fixing tree under terrain is my priority ATM,I haven't looked into forest brush codes yet

**Comment by Quistar-LAB** [comment]
This issue is fixed
