### ISSUE TITLE
Some trees are invisible but come back if building is moved

### ISSUE THREAD

**Issue by chameleon-tbn** [Quistar-LAB/TreeAnarchy#9]
Some trees are missing...

![image](https://user-images.githubusercontent.com/37211016/121069901-5351eb00-c7ce-11eb-82b6-030538b671cd.png)

Using Move itto move a building arround, brings them back

![image](https://user-images.githubusercontent.com/37211016/121070180-af1c7400-c7ce-11eb-8431-f8f9a9efe223.png)

it might be that it is a conflict with e.g. FPS Booster

**Comment by Quistar-LAB** [comment]
I've been trying to fix this problem and its hard to find where this issue is arising from. You can use the terrain tool, and soften the terrain with the least modifier such as 0.1. All the trees will pop back up the terrain. Another way is to select the trees with MoveIt mod and align the trees to terrain height.
After saving, if the trees are still below the ground, then there's something wrong with the way I'm dealing with Ypos.

**Comment by Quistar-LAB** [comment]
Are you using version 0.7.2?

**Comment by chameleon-tbn** [comment]
No, 0.6.2. but i'll restart and see :)

**Comment by Quistar-LAB** [comment]
When you restart, the trees should still be below the terrain. You will have to manually adjust.
Alternatively, you may use an old map that used the old Unlimited Trees mod, and then save it to a new save. The trees should be fixed.

The reason for this is because I had to fix the Y position during save, as it is the only moment when the terrain height is correct. If I do it during loading, the terrain details would not be available, and the Y positions would be all messed up.

Your feedback is valuable, please keep it up

**Comment by chameleon-tbn** [comment]
But you will change this i hope...

**Comment by Quistar-LAB** [comment]
I think this issue is no more. closing
